image: python:3.9

stages:
    - testing
    - deploy

before_script:
    - python -V
    - python -m pip install -r requirements.txt

Django Tests:
    stage: testing

    variables:
        TEST: "TEST"
        DEBUG: "True"

    script:
        - coverage run -m manage test -v 3

    only:
        - merge_request

Deploy Heroku:
    stage: deploy

    script:
        - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master

    only:
        - master
